spring:
  datasource:
    url: jdbc:mysql://localhost:3307/health_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: tynash
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  session:
    store-type: none

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.session.JdbcSessionAutoConfiguration

  docker:
    compose:
      enabled: true
      wait:
        timeout: 120s