version: '3.8'

services:
  health-db:
    image: mysql:8.0
    container_name: health-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: health_db
      MYSQL_USER: tynash
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
